function [ data ] = ReadHillScanASCFileData( filename )
% Reads parameters from Hillger A-Scan measurement files (usally *.asc).
%  
% Syntax
%   data = ReadHillScanASCFileData( filename ) 
%
% Description
%   data = ReadHillScanASCFileData( filename)
%
%   This function read the data stored in ASC-files generated by the
%   commercial available ACUT-System AirTech distributed by Hillger.
%
%    The parameters are:
%
%       filename = ASC file name to be used
%
%       data     = array of measurement data
%
% Implemented by Daniel Hufschläger © 2021
%

%% Initialize variables.
formatSpec = '%d';
headerlines = 73;
dataArray = textread ( filename, formatSpec, 'headerlines', headerlines, 'endofline', '\r\n' );
%% Allocate imported array to column variable names
data = double(dataArray)'*100/2048;
end % function
